### ISSUE TITLE
smooth_earth_heights.m

### ISSUE THREAD

**Issue by alastairUK** [eeveetza/p1812#3]
Looking at the proposed P1812-6 changes in the "dev" branch. I think there's an issue in smooth_earth_heights.m

![image](https://user-images.githubusercontent.com/5337814/159531411-3b71f1f1-089e-4296-a924-f14dfa2979eb.png)

In the revision to -6 this was removed I believe.

-5:
![image](https://user-images.githubusercontent.com/5337814/159531578-b43a7e72-3cfd-4822-8596-b8c512f82bca.png)

-6:
![image](https://user-images.githubusercontent.com/5337814/159531685-9ad56ab3-b094-4105-8ed5-eab9105d71a9.png)

**Comment by eeveetza** [comment]
That is right. Thank you. The correction was done in tl_p1812.m but was unfortunately not implemented in the second instance in smooth_earth_heights.m

%Compute htc and hrc as defined in Table 5 (P.1812-6)
% htc = max(hts,g(1));
% hrc = max(hrs,g(end));
htc = hts;
hrc = hrs;

**Comment by alastairUK** [comment]
👍
