### ISSUE TITLE
Computation of omega

### ISSUE THREAD

**Issue by mplussier** [eeveetza/p1812#9]
Thanks for providing this code.
I think there is a small bug in path_fraction.m. Line 36 should be:
delta = delta + ( d(**start**(i))-d(**start**(i)-1) )/2.0;
instead of
delta = delta + ( d(stop(i))-d(stop(i)-1) )/2.0;

Regards

**Comment by eeveetza** [comment]
Thank you for this @mplussier, well spotted.
The [patch](https://github.com/eeveetza/p1812/commit/0f1c331b23428de1e035d7b0dd8ae74ea6e4de31) should resolve the issue. 
The validation results have also been updated (very minor changes in b2iseac.csv and b2iseac_vertical.csv). The bug did not have any effect for equally spaced profiles (hence, more difficult to spot).

The following tests now give correct results
~~~
d = [0, 10, 12, 14, 16, 18, 20];
zone = [1,2, 2, 2, 2, 2, 3];
path_fraction(d, zone, 1) % should give 0.25
path_fraction(d, zone, 2) % should give 0.7
path_fraction(d, zone, 3) % should give 0.05
~~~
and 
~~~
d = [0, 10, 12, 14, 16, 18, 20];
zone = [1, 2, 3, 1, 2, 3, 1];
path_fraction(d, zone, 1) % should give 0.4
path_fraction(d, zone, 2) % should give 0.4
path_fraction(d, zone, 3) % should give 0.2
~~~
